import { supabase, configured } from './supabase.js';
import { emailValid, phoneValid, fieldError, clearErrors } from './validation.js';
import { initUI, setButtonLoading } from './ui.js';

await initUI();
const message = document.querySelector('#auth-message');
const say = (text, type='info') => { message.textContent = text; message.className = `auth-message show ${type}`; };
const friendly = error => { const m = error?.message?.toLowerCase() || ''; if (m.includes('invalid login')) return 'Email or password is incorrect.'; if (m.includes('already registered')) return 'An account with this email already exists.'; if (m.includes('password should')) return 'Choose a stronger password of at least 8 characters.'; return 'Something went wrong. Please try again.'; };
const returnTo = new URLSearchParams(location.search).get('returnTo') || 'index.html#book';
function showPanel(panel) { document.querySelectorAll('.auth-tab').forEach(b => b.classList.toggle('active', b.dataset.panel === panel)); document.querySelectorAll('.auth-form').forEach(f => f.hidden = f.id !== `${panel}-form`); }
document.querySelectorAll('.auth-tab').forEach(b => b.addEventListener('click', () => showPanel(b.dataset.panel)));
if (location.hash === '#signup') showPanel('signup');
document.querySelectorAll('[data-password-toggle]').forEach(b => b.addEventListener('click', () => { const input = document.querySelector(`#${b.dataset.passwordToggle}`); input.type = input.type === 'password' ? 'text' : 'password'; b.textContent = input.type === 'password' ? 'Show' : 'Hide'; }));
document.querySelector('#signup-password')?.addEventListener('input', e => { const score = [/.{8,}/, /[A-Z]/, /[a-z]/, /\d/, /[^A-Za-z0-9]/].filter(x => x.test(e.target.value)).length; const meter = document.querySelector('.strength span'); meter.style.width = `${score * 20}%`; meter.style.background = score >= 4 ? 'var(--success)' : score >= 3 ? 'var(--warning)' : 'var(--error)'; });
async function ensure() { if (!configured) { say('Add your public Supabase configuration in js/config.js first.', 'error'); return false; } return true; }
document.querySelector('#signup-form')?.addEventListener('submit', async e => { e.preventDefault(); clearErrors(e.currentTarget); if (!await ensure()) return; const f = new FormData(e.currentTarget), name=f.get('full_name').trim(), email=f.get('email').trim(), phone=f.get('phone').trim(), password=f.get('password'), confirm=f.get('confirm_password'); let bad=false; if (!name) { fieldError(e.currentTarget.full_name,'Enter your full name.'); bad=true; } if (!emailValid(email)) { fieldError(e.currentTarget.email,'Please enter a valid email address.'); bad=true; } if (!phoneValid(phone)) { fieldError(e.currentTarget.phone,'Enter a valid Indian mobile number.'); bad=true; } if (password.length < 8) { fieldError(e.currentTarget.password,'Use at least 8 characters.'); bad=true; } if (password !== confirm) { fieldError(e.currentTarget.confirm_password,'Passwords do not match.'); bad=true; } if (bad) return; const b=e.currentTarget.querySelector('[type=submit]'); setButtonLoading(b,true,'Creating account...'); const { data,error }=await supabase.auth.signUp({email,password,options:{emailRedirectTo:new URL('auth.html',location.href).href,data:{full_name:name,phone}}}); setButtonLoading(b,false); if(error){say(friendly(error),'error');return;} if(data.session){location.href=returnTo;}else say('Account created. Check your email to verify your address before signing in.','info'); });
document.querySelector('#login-form')?.addEventListener('submit', async e => { e.preventDefault(); clearErrors(e.currentTarget); if (!await ensure()) return; const f=new FormData(e.currentTarget),email=f.get('email').trim(),password=f.get('password');let bad=false;if(!emailValid(email)){fieldError(e.currentTarget.email,'Please enter a valid email address.');bad=true;}if(!password){fieldError(e.currentTarget.password,'Enter your password.');bad=true;}if(bad)return;const b=e.currentTarget.querySelector('[type=submit]');setButtonLoading(b,true,'Signing in...');const{error}=await supabase.auth.signInWithPassword({email,password});setButtonLoading(b,false);if(error){say(friendly(error),'error');return;}location.href=returnTo; });
document.querySelector('#forgot-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!await ensure())return;const email=new FormData(e.currentTarget).get('email').trim();if(!emailValid(email)){say('Please enter a valid email address.','error');return;}const b=e.currentTarget.querySelector('button');setButtonLoading(b,true,'Sending link...');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:new URL('auth.html?mode=reset',location.href).href});setButtonLoading(b,false);say(error?friendly(error):'If an account exists, a password reset link has been sent.',error?'error':'info');});
if(new URLSearchParams(location.search).get('mode')==='reset'){showPanel('reset');}
document.querySelector('#reset-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!await ensure())return;const password=new FormData(e.currentTarget).get('password');if(password.length<8){say('Use at least 8 characters.','error');return;}const b=e.currentTarget.querySelector('button');setButtonLoading(b,true,'Updating password...');const{error}=await supabase.auth.updateUser({password});setButtonLoading(b,false);if(error){say(friendly(error),'error');return;}say('Password updated. You can now continue.','info');setTimeout(()=>location.href=returnTo,800);});
